In [158]:
from pymatgen.core import Structure
import numpy as np

def round_to_value(a):
    multiplier = a/0.125
    rounded_multiplier = np.round(multiplier, 0)
    return rounded_multiplier * 0.125

def reorder(a):
    position = [0, 1, 2]
    for i in position:
        if a[i] == 1.:
            a[i] = 0
    
strc = Structure.from_file('./initial/')
ref = Structure.from_file('./prim_inverse.cif')

for atom in strc:
    strc_corrected = (round_to_value(atom.frac_coords))
    atom.frac_coords = strc_corrected
    reorder(atom.frac_coords)
    
for atom1 in strc:
    print(atom1.frac_coords, atom1.species)
    for atom2 in ref:
        if np.array_equal((atom1.frac_coords), (atom2.frac_coords), equal_nan=False) == True:
            if atom2.species_string == 'Na':
                print(f'{atom1.frac_coords} is 8b')
            elif atom2.species_string == 'Li':
                print(f'{atom1.frac_coords} is 8a')
            elif atom2.species_string == 'Mg':
                print(f'{atom1.frac_coords} is 16d')
            elif atom2.species_string == 'Be':
                print(f'{atom1.frac_coords} is 16c')
            elif atom2.species_string == 'Nb':
                print(f'{atom1.frac_coords} is 48f')
            elif atom2.species_string == 'O':
                print(f'{atom1.frac_coords} is 32e')
        else:
            continue

[0.375 0.375 0.875] Li1
[0.375 0.375 0.875] is 8a
[0.25 0.   0.25] Li1
[0.25 0.   0.25] is 16c
[0.75 0.75 0.  ] Li1
[0.75 0.75 0.  ] is 16c
[0.   0.75 0.75] Li1
[0.   0.75 0.75] is 16c
[0.5 0.  0.5] Li1
[0.5 0.  0.5] is 16c
[0.625 0.625 0.375] Li1
[0.625 0.625 0.375] is 48f
[0.5 0.5 0.5] Li1
[0.5 0.5 0.5] is 16d
[0.25 0.75 0.  ] Li1
[0.25 0.75 0.  ] is 16d
[0.75 0.5  0.75] Li1
[0.75 0.5  0.75] is 16d
[0.25 0.25 0.5 ] Li1
[0.25 0.25 0.5 ] is 16d
[0.5 0.  0. ] Li1
[0.5 0.  0. ] is 16d
[0.5  0.25 0.25] Li1
[0.5  0.25 0.25] is 16d
[0.   0.75 0.25] Li1
[0.   0.75 0.25] is 16d
[0.75 0.75 0.5 ] Li1
[0.75 0.75 0.5 ] is 16d
[0.25 0.   0.75] Li1
[0.25 0.   0.75] is 16d
[0.75 0.   0.25] Li1
[0.75 0.   0.25] is 16d
[0.  0.5 0. ] Li1
[0.  0.5 0. ] is 16d
[0.5  0.75 0.75] Sc1
[0.5  0.75 0.75] is 16d
[0.25 0.5  0.25] Sc1
[0.25 0.5  0.25] is 16d
[0.   0.25 0.75] Sc1
[0.   0.25 0.75] is 16d
[0.75 0.25 0.  ] Sc1
[0.75 0.25 0.  ] is 16d
[0.  0.  0.5] Sc1
[0.  0.  0.5] is 16d
[0.25 0.25 0.25] Cl1
[0.25 0.

In [159]:
from pymatgen.core import Structure
from pymatgen.io.cif import CifWriter
import numpy as np

def round_to_value(a):
    multiplier = a/0.125
    rounded_multiplier = np.round(multiplier, 0)
    return rounded_multiplier * 0.125

def reorder(a):
    position = [0, 1, 2]
    for i in position:
        if a[i] == 1.:
            a[i] = 0
    
strc = Structure.from_file('./initial/il0015300046_initial_P1.cif')
ref = Structure.from_file('./prim_inverse.cif')

for atom in strc:
    strc_corrected = (round_to_value(atom.frac_coords))
    atom.frac_coords = strc_corrected
    reorder(atom.frac_coords)

positions = np.arange(0, 54)    

for atom1 in strc:
    for atom2 in ref:
        if np.array_equal((atom1.frac_coords), (atom2.frac_coords), equal_nan=False) == True:
            if atom2.species_string == 'Na':
                print(f'{atom1.coords} is 8b')
            elif atom2.species_string == 'Li':
                print(f'{atom1.coords} is 8a')
            elif atom2.species_string == 'Be':
                print(f'{atom1.coords} is 16c')
            elif atom2.species_string == 'Nb':
                print(f'{atom1.coords} is 48f')
        else:
            continue

to_delete = []            
            
for atom1, label in zip(strc, positions):
    for atom2 in ref:
        if np.array_equal((atom1.frac_coords), (atom2.frac_coords), equal_nan=False) == True:
            if atom2.species_string == 'Na':
                to_delete.append(label)
            elif atom2.species_string == 'Li':
                to_delete.append(label)
            elif atom2.species_string == 'Be':
                to_delete.append(label)
            elif atom2.species_string == 'Nb':
                to_delete.append(label)
        else:
            continue

to_delete.sort(reverse=True)            
            
for d in to_delete:
    del strc[d]
    
for atom1 in strc:
    for atom2 in ref:
        if np.array_equal((atom1.frac_coords), (atom2.frac_coords), equal_nan=False) == True:
            if atom2.species_string == 'Na':
                print(f'{atom1.coords} is 8b')
            elif atom2.species_string == 'Li':
                print(f'{atom1.coords} is 8a')
            elif atom2.species_string == 'Be':
                print(f'{atom1.coords} is 16c')
            elif atom2.species_string == 'Nb':
                print(f'{atom1.coords} is 48f')
        else:
            continue
            
print(len(strc))
    
w = CifWriter(strc)
w.write_file('./ordered/il0015300046_ordered_P1.cif')

[3.9013875 3.9013875 9.1032375] is 8a
[2.600925 0.       2.600925] is 16c
[7.80277500e+00 7.80277500e+00 9.55564343e-16] is 16c
[-4.77782171e-16  7.80277500e+00  7.80277500e+00] is 16c
[5.20185 0.      5.20185] is 16c
[6.5023125 6.5023125 3.9013875] is 48f
48


In [189]:
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

spnl = Structure.from_file('./ordered/eta.cif')

spg = SpacegroupAnalyzer(structure=spnl, symprec=0.01, angle_tolerance=5.0)
spg.get_space_group_symbol()
spg_symbol = spg.get_space_group_symbol()
lattice_type = spg.get_lattice_type()
crystal_system = spg.get_crystal_system()

In [190]:
spg.get_space_group_symbol()

'C2/m'