In [34]:
from pymatgen.core import Structure
from pymatgen.io.cif import CifWriter
import numpy as np

def round_to_value(a):
    multiplier = a/0.125
    rounded_multiplier = np.round(multiplier, 0)
    return rounded_multiplier * 0.125

def reorder(a):
    position = [0, 1, 2]
    for i in position:
        if a[i] == 1.:
            a[i] = 0
    
strc = Structure.from_file('./initial/monoclinic.cif')
ref = Structure.from_file('./prim_inverse.cif')

for atom in strc:
    strc_corrected = (round_to_value(atom.frac_coords))
    atom.frac_coords = strc_corrected
    reorder(atom.frac_coords)

positions = np.arange(0, 54)
    
for atom1 in strc:
    for atom2 in ref:
        if np.array_equal((atom1.frac_coords), (atom2.frac_coords), equal_nan=False) == True:
            if atom2.species_string == 'Na':
                print(f'{atom1.coords} is 8b')
            elif atom2.species_string == 'Li':
                print(f'{atom1.coords} is 8a')
            elif atom2.species_string == 'Be':
                print(f'{atom1.coords} is 16c')
            elif atom2.species_string == 'Nb':
                print(f'{atom1.coords} is 48f')
        else:
            continue

[3.9013875 3.9013875 9.1032375] is 8a
[2.60092500e+00 2.60092500e+00 3.18521448e-16] is 16c
[2.600925 5.20185  7.802775] is 16c
[5.20185 0.      5.20185] is 16c
[5.20185000e+00 5.20185000e+00 6.37042895e-16] is 16c
[1.3004625 9.1032375 3.9013875] is 48f


In [6]:
from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import glob

structure = glob.glob('./find_cubic/li11sc5cl32/sup*.cif')

groups = {}

for s in structure:
    strc = Structure.from_file(s)

    spg = SpacegroupAnalyzer(structure=strc, symprec=0.01, angle_tolerance=5.0)
    
    groups[s] = spg.get_space_group_symbol()
    
groups

{'./find_cubic/li11sc5cl32/supercell_i0007_w96.cif': 'Cm',
 './find_cubic/li11sc5cl32/supercell_i0017_w96.cif': 'Cm',
 './find_cubic/li11sc5cl32/supercell_i0015_w192.cif': 'P1',
 './find_cubic/li11sc5cl32/supercell_i0028_w96.cif': 'Cm',
 './find_cubic/li11sc5cl32/supercell_i0021_w192.cif': 'P1',
 './find_cubic/li11sc5cl32/supercell_i0020_w192.cif': 'P1',
 './find_cubic/li11sc5cl32/supercell_i0031_w96.cif': 'C2',
 './find_cubic/li11sc5cl32/supercell_i0002_w192.cif': 'P1',
 './find_cubic/li11sc5cl32/supercell_i0034_w48.cif': 'C2/m',
 './find_cubic/li11sc5cl32/supercell_i0008_w192.cif': 'P1',
 './find_cubic/li11sc5cl32/supercell_i0009_w192.cif': 'P1',
 './find_cubic/li11sc5cl32/supercell_i0029_w96.cif': 'C2',
 './find_cubic/li11sc5cl32/supercell_i0004_w96.cif': 'Cm',
 './find_cubic/li11sc5cl32/supercell_i0014_w96.cif': 'C2',
 './find_cubic/li11sc5cl32/supercell_i0013_w192.cif': 'P1',
 './find_cubic/li11sc5cl32/supercell_i0005_w96.cif': 'C2',
 './find_cubic/li11sc5cl32/supercell_i0018_w192

In [72]:
spg.get_space_group_symbol()

'C222_1'

In [ ]:
spg_symbol = spg.get_space_group_symbol()
lattice_type = spg.get_lattice_type()
crystal_system = spg.get_crystal_system()