In [1]:
from pymatgen.core import Structure
from pymatgen.io.cif import CifWriter
import numpy as np

def round_to_value(a):
    multiplier = a/0.125
    rounded_multiplier = np.round(multiplier, 0)
    return rounded_multiplier * 0.125

def reorder(a):
    position = [0, 1, 2]
    for i in position:
        if a[i] == 1.:
            a[i] = 0
    
strc = Structure.from_file('il0004187328_initial_P1.cif')
ref = Structure.from_file('./prim_inverse_noli.cif')

for atom in strc:
    strc_corrected = (round_to_value(atom.frac_coords))
    atom.frac_coords = strc_corrected
    reorder(atom.frac_coords)

positions = np.arange(0, 54)

mobile_sites = []

for atom1 in strc:
    for atom2 in ref:
        if np.array_equal((atom1.frac_coords), (atom2.frac_coords), equal_nan=False) == True:
            if atom2.species_string == 'Na':
                print(f'{atom1.frac_coords} is 8b')
                mobile_sites.append(atom1)
            elif atom2.species_string == 'Ca':
                print(f'{atom1.frac_coords} is 8a')
                mobile_sites.append(atom1)
            elif atom2.species_string == 'Be':
                print(f'{atom1.frac_coords} is 16c')
                mobile_sites.append(atom1)
            elif atom2.species_string == 'Nb':
                print(f'{atom1.frac_coords} is 48f')
                mobile_sites.append(atom1)

mobile_indices = [i for i, site in enumerate(list(mobile_sites))]                
                
for mob in mobile_indices:
    strc[mob].species = 'Na'

# Sort so that 'mobile' Li are put first
strc.sort()    
    
#strc.make_supercell([2,2,2])    
    
mobile_li = [i for i, site in enumerate(list(strc)) if site.species_string == 'Na']

for li in mobile_li:
    strc[li].species = 'Li'
                
w = CifWriter(strc)
w.write_file(f'monoclinic_1.cif')

[0.375 0.375 0.875] is 8a
[0.25 0.75 0.5 ] is 16c
[0.   0.75 0.75] is 16c
[0.75 0.5  0.25] is 16c
[0.5 0.  0.5] is 16c
[0.125 0.875 0.125] is 48f


In [ ]:
from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import glob

structure = glob.glob('./find_cubic/li11sc5cl32/sup*.cif')

groups = {}

for s in structure:
    strc = Structure.from_file(s)

    spg = SpacegroupAnalyzer(structure=strc, symprec=0.01, angle_tolerance=5.0)
    
    groups[s] = spg.get_space_group_symbol()
    
groups

In [ ]:
spg.get_space_group_symbol()

In [ ]:
spg_symbol = spg.get_space_group_symbol()
lattice_type = spg.get_lattice_type()
crystal_system = spg.get_crystal_system()